spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/voting
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true   # 데이터 베이스 초기화 시점을 지연
    properties:
      hibernate.format_sql: true
      hibernate.dialect : org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode : always
